name: Step 4b # Copilot on GitHub

on:
  # Trigger if PR Description is edited
  # Disabled because PR summaries are not available for free accounts
  # pull_request:
  #   branches:
  #     - main
  #   types:
  #     - edited

  # Trigger if Copilot adds a review comment
  pull_request_review:

permissions:
  contents: write
  actions: write
  issues: write
  pull-requests: read
  repository-projects: read

jobs:
  find_exercise:
    name: Find Exercise Issue
    uses: skills/exercise-toolkit/.github/workflows/find-exercise-issue.yml@main

  check_step_work:
    name: Check step work
    runs-on: ubuntu-latest
    needs: [find_exercise]
    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.find_exercise.outputs.issue-number }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: main

      # START: Check practical exercise

      - name: Check for PR description
        continue-on-error: true
        id: check-pr-description
        run: |
          # Check if PR has a description and minimum length
          min_length=15
          body_length=$(echo "$PR_Body" | wc -c)
          echo "PR description length: $body_length"

          if [ "$body_length" -lt $min_length ]; then
            echo "::error::PR description is too short or missing"
            exit 1
          fi
        env:
          PR_Body: ${{ github.event.pull_request.body }}

      - name: Check for Copilot review
        continue-on-error: true
        id: check-copilot-review
        run: |
          # Check for a PR Review from Copilot
          reviews=$(gh pr view --repo $REPO $PR_NUMBER --json reviews)
          authors=$(echo "$reviews" | jq '.reviews[].author.login')

          if echo "$authors" | grep -q "copilot-pull-request-reviewer"; then
            echo "Copilot has reviewed this PR."
          else
            echo "Copilot has NOT reviewed this PR."
            echo "::error::No review from Copilot found"
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Create comment - step results
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: exercise-toolkit/markdown-templates/step-feedback/step-results-table.md
          vars: |
            step_number: 4
            results_table:
              - description: "Pull request contains a descriptive overview"
                passed: ${{ steps.check-pr-description.outcome == 'success' }}
              - description: "Pull request received a review from GitHub Copilot"
                passed: ${{ steps.check-copilot-review.outcome == 'success' }}
            tips:
              - "If you already requested Copilot review and this check did not pass, go to your repository [actions](https://github.com/${{ github.repository }}/actions) tab to check if a workflow run is awaiting your manual approval."
              - "You can use repository rulesets to automatically require a review from Copilot."

      - name: Fail job if not all checks passed
        if: contains(steps.*.outcome, 'failure')
        run: exit 1

      # END: Check practical exercise
